blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/rebuildup/my-web-2025/discussions
    about: ä¸€èˆ¬çš„ãªè³ªå•ã‚„ã‚¢ã‚¤ãƒ‡ã‚¢ã®å…±æœ‰ã¯ã“ã¡ã‚‰ã§
  - name: ğŸ“§ ãƒ¡ãƒ¼ãƒ«
    url: mailto:rebuild.up.up(at)gmail.com
    about: ç›´æ¥é€£çµ¡ãŒå¿…è¦ãªå ´åˆã¯ãƒ¡ãƒ¼ãƒ«ã§
